### ISSUE TITLE
Rojo Roadmap

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#1]
Aim high!

Bold things are high-impact changes. Hoping to do things in roughly this order:

* [ ] Fix pile of bugs reported by Tiffany
* [ ] Implement write/delete support in the server
* [ ] Build a nifty UI in [Roact](https://github.com/Roblox/Roact)
* [ ] Handle server mismatch and configuration storage
* [ ] Sync scripts bi-directionally
* [ ] Sync JSON models into Studio (from [Studio Bridge](https://github.com/vocksel/studio-bridge))
* [ ] Sync rbxmx/rbxlx models into Studio (reference: [Elixir](https://github.com/vocksel/elixir))
* [ ] Sync models onto filesystem in either JSON or rbxmx/rbxlx

**Comment by LPGhatguy** [comment]
Current priority is the stateful IDs rewrite (#44) which will lay the groundwork for the rest of the year.

**Comment by LPGhatguy** [comment]
Welcome to 2019, not all of these things are done, but substantial progress has been made!

**Comment by Kampfkarren** [comment]
>  0.5.0 Release

Check this one off!
