### ISSUE TITLE
SharedString tracking issue

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/rojo#184]
Steps to implementation:

- [x] rbx_dom_weak implementation (https://github.com/LPGhatguy/rbx-dom/issues/60)
- [x] XML format support (https://github.com/LPGhatguy/rbx-dom/issues/61)
- [x] Upgraded and in Rojo
